name: Render Reel Video & Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Prepare paths
        run: |
          mkdir -p output tmp
          rm -rf output/* tmp/*

      - name: Run script
        run: |
          chmod +x script.sh
          ./script.sh

      - name: Upload output as artifact (1 day retention)
        uses: actions/upload-artifact@v4
        with:
          name: final-video
          path: output/
          retention-days: 1   # automatically deletes after 1 day

      - name: Upload to Google Drive
        uses: prabirshrestha/action-google-drive@v1
        with:
          json_key: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          folder_id: 1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH
          src: output/*
