name: Test Google Drive Service Account

on:
  workflow_dispatch:

jobs:
  test-drive:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Write Service Account JSON
        run: echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" > /tmp/sa.json

      - name: Test Service Account
        run: |
          rclone about drive: \
            --drive-service-account-file /tmp/sa.json \
            --drive-root-folder-id 1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH
