name: Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Save service account JSON
        run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" > /tmp/sa.json

      - name: Upload file to Google Drive
        run: |
          rclone copy ./spotify.png drive: \
            --drive-service-account-file /tmp/sa.json \
            --drive-root-folder-id 1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH \
            -P
