name: Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Save Service Account JSON
        env:
          SA_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        run: |
          echo "$SA_JSON" > /tmp/sa.json

      - name: Test Google Drive access
        run: |
          rclone about drive: \
            --drive-service-account-file /tmp/sa.json \
            --drive-root-folder-id 1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH

      - name: Upload file to Google Drive
        run: |
          rclone copy ./spotify.png drive: \
            --drive-service-account-file /tmp/sa.json \
            --drive-root-folder-id 1EVIHk24_3C7DsCLcYoQOdrM_T11UrkWH \
            -P
