name: Render Reel Video

on:
  workflow_dispatch:
  push:
  schedule:
    # 09:30 UTC = 15:00 IST (3 PM)
    - cron: '30 9 * * *'
    # 10:30 UTC = 16:00 IST (4 PM)
    - cron: '30 10 * * *'
    # 11:30 UTC = 17:00 IST (5 PM)
    - cron: '30 11 * * *'
    # 12:30 UTC = 18:00 IST (6 PM)
    - cron: '30 12 * * *'
    # 13:30 UTC = 19:00 IST (7 PM)
    - cron: '30 13 * * *'
    # 14:30 UTC = 20:00 IST (8 PM)
    - cron: '30 14 * * *'

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Run Everything
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          SHEETDB_URL: ${{ secrets.SHEETDB_URL }}
        run: |
          chmod +x zapier.sh
          ./zapier.sh
